spring:
  profiles:
    active: local
  application:
    name: yu-ai-agent
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: ${zuimeng.zijie.api-key}
      base-url: ${zuimeng.zijie.base-url}
      chat:
        options:
          model: ${zuimeng.zijie.model}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zuimeng.yuaiagent.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
  servlet:
    context-path: /zuimeng
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - com.zuimeng.yuaiagent.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
#logging:
#  level:
#    org.springframework.web.client: debug